config/routes.rb
Rails.application.routes.draw do

  get '/auth/:provider/callback' => 'sessions#omniauth'
  
  get '/logout', to: 'sessions#logout'

  get '/login', to: 'sessions#login'
  post '/login', to: 'sessions#create'

  get '/signup', to: 'users#new'
  
  resources :users

  resources :cookbooks do
    resources :recipes
  end



  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cookbook.rb
class Cookbook < ApplicationRecord
    validates :title, presence: true, uniqueness: { case_sensitive: false }
    validates :description, presence: true, uniqueness: { case_sensitive: false }

    has_many :recipes
    has_many :users, through: :recipes
    
    scope :order_by_name, -> { order(title: :asc) }

end

app/models/recipe.rb
class Recipe < ApplicationRecord
    validates :user_id, presence: true
    validates :cookbook_id, presence: true
    validates :title, presence: true, uniqueness: { case_sensitive: false }
    validates :description, presence: true, uniqueness: { case_sensitive: false }

    belongs_to :user
    belongs_to :cookbook
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :recipes
  has_many :cookbooks, through: :recipes 
  
  validates :username, presence: true, uniqueness: { case_sensitive: false }
  validates :email, presence: true, uniqueness: { case_sensitive: false }
  validates :password, presence: true


  def self.from_omniauth(response)
    User.find_or_create_by(uid: response[:uid], provider: response[:provider]) do |u|
      u.username = response[:info][:name]
      u.email = response[:info][:email]
      u.password = SecureRandom.hex(15)
      # byebug
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
#all can be used in all C

    def logged_in?
        !!current_user
    end

    def logout!
        session.clear
    end
    
    def current_user
        @current_user ||= User.find_by(:username => session[:username]) if session[:username]
    end
    
    def redirect_if_not_logged_in
        redirect_to :root unless logged_in?
    end
    
    def redirect_already_logged_in
        if current_user
          redirect_to :user, notice: "You are already logged in!"
        end
    end

end

app/controllers/cookbooks_controller.rb
class CookbooksController < ApplicationController

    def index
        @cookbooks = Cookbook.order_by_name
    end

    def show 
        @cookbook = Cookbook.find(params[:id])
        @recipe = Recipe.new
        @recipes = @cookbook.recipes
    end

    def new
        @cookbook = Cookbook.new
    end
    
    def create 
        @cookbook = Cookbook.new(cookbook_params)
            if @cookbook.save
                redirect_to @cookbook
            else
                render 'new'
            end
    end

    def edit
    end

    def update 
    end

    def destroy 
    end

    private

    def cookbook_params
        params.require(:cookbook).permit(:title, :description)
    end

end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
    
    def index
        @cookbook = Cookbook.find(params[:cookbook_id])
        @recipes = @cookbook.recipes
    end

    def show
        @cookbook = Cookbook.find(params[:cookbook_id])
        @recipe = Recipe.find(params[:id])
    end

    def new
        @recipe = Recipe.new
    end

    def create 
        @cookbook = Cookbook.find(params[:cookbook_id])
        @recipe = Recipe.new(recipe_params)
        @recipe.cookbook_id = @cookbook.id
        @recipe.user_id = User.find_by(:username => session[:username]).id
            if @recipe.save
                redirect_to cookbook_recipe_path(@cookbook, @recipe)
            else
                flash[:messages] = @recipe.errors.full_messages
                redirect_to @cookbook
            end
    end

    def edit
    end

    def update 

    end

    def destroy 
    end

    private

    def recipe_params
        params.permit(:title, :description)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
before_action :redirect_already_logged_in, only: [:new]
before_action :dynamic_background, only: [:new]

    def omniauth
        user = User.from_omniauth(request.env['omniauth.auth'])
        # byebug
        if user.valid?
            session[:user_id] = user.id
            redirect_to user_path(user.id)
        else
            flash[:message] = user.errors.full_messages.join(", ")
            redirect_to '/login'
        end
    end

    def login
    end

    def create
        @user = User.find_by(username: params[:user][:username])
        if @user && @user.authenticate(params[:user][:password])
            session[:user_id] = @user.id
            redirect_to user_path(@user)
        else
            redirect_to :login, notice: "Please try again. Your login was not successful."
        end 
    end

    def logout
        session.clear
        redirect_to :login
    end

    private

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_current_user, only: [:show]

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:username] = @user.username
            redirect_to user_path(current_user)
            # byebug
        else
            redirect_to :root
        end
    end

    def show #must be in block to show in V, used before action
        @user = params[:id]
    end

    private

    def user_params
        params.require(:user).permit(:username, :email, :password)
    end

    def set_current_user
        @current_user = current_user
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

    def current_user
        @current_user ||= User.find_by_id(session[:user_id])  
    end

end

app/helpers/cookbooks_helper.rb
module CookbooksHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/cookbooks/edit.html.erb
<h1>Cookbook Edit</h1>

app/views/cookbooks/index.html.erb
<h1>Your Cookbooks!</h1>

<ul>
    <% @cookbooks.each do |cookbook| %>
        <li><%= link_to cookbook.title, cookbook_path(cookbook) %></li>
    <% end %>
</ul>

app/views/cookbooks/new.html.erb
<h1>Let's Create a New Cookbook!</h1>

<%= form_for(@cookbook) do |f| %>

<div>
    <%= f.label :title %>
    <%= f.text_field :title %>
    
    <%= f.label :description %>
    <%= f.text_field :description %>
    
    <%= f.submit%>
</div>
<% end %>


<li><%= link_to "All Cookbooks", cookbooks_path %></li>

app/views/cookbooks/show.html.erb
<h1>Cookbook Show</h1>

<h1><%= @cookbook.title %></h1>
<p><%= @cookbook.description %></p>

<h3>Your List of Recipes:</h3>
<% @recipes.each do |recipe| %>
<%= link_to recipe.title, cookbook_recipe_path(recipe) %><br/>
<% end %>

<h3>Add a new Recipe:</h3>


<% if flash[:messages]%>
      <h3>Error(s):</h3>
      <ul>
        <% flash[:messages].each do |message|%>
        <li><%= message %></li>
      </ul>
      <% end %>
<% end %>


<%= form_with url: cookbook_recipes_path(@cookbook,@recipe) do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %><br/>
    
    <%= f.label :description %>
    <%= f.text_field :description %><br/>
    
    <%= f.submit%>
<% end %>

<br/><%= link_to "All Cookbooks", cookbooks_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>reciPals: The Ultimate Recipe Sharing App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/recipes/index.html.erb
<h1>Recipes Index</h1>

<ul>
    <% @recipes.each do |recipes| %>
        <li><%= link_to recipes.title, recipes_path(recipes) %></li>
    <% end %>
</ul>

app/views/recipes/new.html.erb
<h1>New Recipes</h1>

<%= form_for(@recipe) do |f| %>

<div>
    <%= f.label :title %>
    <%= f.text_field :title %>
    
    <%= f.label :description %>
    <%= f.text_field :description %>
    
    <%= f.submit%>
</div>
<% end %>


<li><%= link_to "All Recipes", recipes_path %></li>

app/views/recipes/show.html.erb
<h1><%= @recipe.title %></h1>

<p><%= @recipe.description %></p>

<br/><%= link_to "Go back to #{@cookbook.title}", @cookbook %>

app/views/users/new.html.erb
<h1>Sign Up Here to Use reciPals!</h1>

<%= form_for(@user) do |f| %>

    <%= f.label :username, "Username:" %>
    <%= f.text_field :username %>

    <%= f.label :email, "Email:" %>
    <%= f.text_field :email %>

    <%= f.label :password, "Password:" %>
    <%= f.password_field :password %><br/>

    <%= f.submit "Sign Up!" %>

<% end %>

app/views/users/show.html.erb
<h1>Welcome to Your Home Page!</h1>

<h2> Hello, <%= current_user.username.capitalize %>! </h2>